CREATE TABLE index_details
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    index_type     VARCHAR(255)                            NOT NULL,
    sub_index_type VARCHAR(255)                            NOT NULL,
    exchange       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_index_details PRIMARY KEY (id)
);

ALTER TABLE index_details
    ADD CONSTRAINT uc_index_details_name UNIQUE (name);

CREATE TABLE index_nav
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nav_date        date                                    NOT NULL,
    net_asset_value DECIMAL                                 NOT NULL,
    index_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_index_nav PRIMARY KEY (id)
);

ALTER TABLE index_nav
    ADD CONSTRAINT uc_index_nav_nadaneasva UNIQUE (nav_date, net_asset_value);

ALTER TABLE index_nav
    ADD CONSTRAINT FK_INDEX_NAV_ON_INDEX FOREIGN KEY (index_id) REFERENCES index_details (id);

CREATE TABLE index_rolling_return_stats
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year_nos       BIGINT                                  NOT NULL,
    std_dev        DECIMAL(10, 2),
    mean           DECIMAL(10, 2),
    percentile_90  DECIMAL(10, 2),
    percentile_95  DECIMAL(10, 2),
    negative_count DECIMAL(10, 2)                          NOT NULL,
    count_5        DECIMAL(10, 2)                          NOT NULL,
    count_10       DECIMAL(10, 2)                          NOT NULL,
    count_15       DECIMAL(10, 2)                          NOT NULL,
    count_20       DECIMAL(10, 2)                          NOT NULL,
    count_25       DECIMAL(10, 2)                          NOT NULL,
    total_count    DECIMAL(10, 2)                          NOT NULL,
    starting_year  BIGINT                                  NOT NULL,
    index_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_index_rolling_return_stats PRIMARY KEY (id)
);

ALTER TABLE index_rolling_return_stats
    ADD CONSTRAINT FK_INDEX_ROLLING_RETURN_STATS_ON_INDEX FOREIGN KEY (index_id) REFERENCES index_details (id);