app:
  index:
    sink:
      file:
        folderPath: "C:/Jubin/temp/indexdata"



logging:
  level:
    org:
      atmosphere: warn
      apache:
        hc:
          client5:
            http: debug

spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"
  datasource:
    url:  jdbc:h2:tcp://localhost/C:/Jubin/dev/data/db/h2/mfnav
    username: sa
    #password: JM8$tek12
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.H2Dialect

