INSERT INTO index_details (name, index_type, sub_index_type, exchange)
VALUES ('NIFTY 50','Equity','Broad Market Indices','NSE'),
       ('NIFTY NEXT 50','Equity','Broad Market Indices','NSE'),
       ('NIFTY SMALLCAP 50','Equity','Broad Market Indices','NSE'),
       ('NIFTY SMALLCAP 250','Equity','Broad Market Indices','NSE'),
       ('NIFTY MIDCAP 50','Equity','Broad Market Indices','NSE'),
       ('NIFTY MIDCAP 150','Equity','Broad Market Indices','NSE'),
       ('NIFTY MICROCAP 250','Equity','Broad Market Indices','NSE'),
       ('NIFTY LARGEMIDCAP 250','Equity','Broad Market Indices','NSE'),
       ('NIFTY BANK','Equity','Sectoral Indices','NSE'),
       ('NIFTY IT','Equity','Sectoral Indices','NSE'),
       ('NIFTY ALPHA LOW-VOLATILITY 30','Equity','Strategy Indices','NSE'),
       ('NIFTY500 VALUE 50','Equity','Strategy Indices','NSE'),
       ('NIFTY500 MULTICAP MOMENTUM QUALITY 50','Equity','Strategy Indices','NSE'),
       ('NIFTY200 MOMENTUM 30','Equity','Strategy Indices','NSE'),
       ('NIFTY50 VALUE 20','Equity','Strategy Indices','NSE'),
       ('NIFTY50 EQUAL WEIGHT','Equity','Strategy Indices','NSE'),
       ('NIFTY MIDCAP150 QUALITY 50','Equity','Strategy Indices','NSE'),
       ('NIFTY MIDCAP150 MOMENTUM 50','Equity','Strategy Indices','NSE');
